# Generated by Django 5.1.4 on 2024-12-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(choices=[('toyota', 'Toyota'), ('honda', 'Honda'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('bmw', 'BMW'), ('audi', 'Audi'), ('mercedes', 'Mercedes-Benz'), ('nissan', 'Nissan'), ('volkswagen', 'Volkswagen'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('mazda', 'Mazda'), ('subaru', 'Subaru'), ('lexus', 'Lexus'), ('infiniti', 'Infiniti'), ('acura', 'Acura'), ('mitsubishi', 'Mitsubishi'), ('porsche', 'Porsche'), ('jaguar', 'Jaguar'), ('land_rover', 'Land Rover'), ('fiat', 'Fiat'), ('alfa_romeo', 'Alfa Romeo'), ('volvo', 'Volvo'), ('tesla', 'Tesla')], max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED_EXCELLENT', 'Used - Excellent'), ('USED_GOOD', 'Used - Good'), ('USED_BAD', 'Used - Bad'), ('USED', 'Used')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
