# Generated by Django 5.1.4 on 2024-12-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RandDealer', '0002_alter_cars_id_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USED_EXCELLENT', 'Used - Excellent'), ('USED_GOOD', 'Used - Good'), ('USED_BAD', 'Used - Bad'), ('USED', 'Used')], default='Choose one', max_length=20),
        ),
    ]
