# Generated by Django 5.1.4 on 2024-12-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RandDealer', '0003_alter_cars_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='condition',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('USED_EXCELLENT', 'Used - Excellent'), ('USED_GOOD', 'Used - Good'), ('USED_BAD', 'Used - Bad'), ('USED', 'Used')], default='Choose', max_length=20, null=True),
        ),
    ]
