# Generated by Django 5.1.4 on 2024-12-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RandDealer', '0005_alter_cars_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
