# Generated by Django 5.1.4 on 2025-04-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RandDealer', '0011_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
