# Generated by Django 5.1.4 on 2025-05-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RandDealer', '0013_alter_cars_condition_alter_cars_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(),
        ),
    ]
