# Generated by Django 5.1.4 on 2025-05-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RandDealer', '0014_alter_cars_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.IntegerField(),
        ),
    ]
